! * ==========================================================
! * File:       hdfeos5_64.inc
! * Author:     A. Muslimov, Emergent Technology Services, Inc.
! * Date:       March 19, 2002
! * Purpose:    Fortran header file for HDFEOS5 routines on 64
! *              bit platforms
! * ==========================================================
! * Contents: 
! *
! *
! * ===========================================================
 

           integer*8 HE5S_UNLIMITED_F_64

           parameter(HE5S_UNLIMITED_F_64 = -1)
